---
# tasks main file for docker-role
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Ubuntu.yml
  when: ansible_os_family == 'Debian'

- include_tasks: docker-users.yml